[theme]
primaryColor = "#3B82F6"
backgroundColor = "#080A0F"
secondaryBackgroundColor = "#0E131F"
textColor = "#F1F5F9"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
